### ISSUE TITLE
Player can pickup items using hoper

### ISSUE THREAD

**Issue by Bodyash** [diecode/KillerMoney#12]
Item-drop:
      Enabled: true

So players can pick up it buy hopper and rename by anvil
https://www.youtube.com/watch?v=aLym7ijUjKg

**Comment by Bodyash** [comment]
Can be fixed with #13

**Comment by Bodyash** [comment]
Tested with my fix. It`s all ok.

**Comment by kgahor** [comment]
Thank you your pr, I migrated.
