### ISSUE TITLE
Plugin Commands/Perms Not Working

### ISSUE THREAD

**Issue by ghost** [diecode/KillerMoney#14]
I have a problem with the plugin, and I think others also have this problem-
When I try and do /km help it responds by telling me:
Please type /km help
I am running 1.11.2 craftbukkit, and I don't realize anything wrong in the console other than:
[07:50:17 ERROR]: Error occurred while enabling KillerMoney v4.1.0 (Is it up to date?)

Please help, Thank You in advance :D

**Comment by kgahor** [comment]
Please check the latest version (4.1.1)
