### ISSUE TITLE
Problem with OPs

### ISSUE THREAD

**Issue by bryanquatremare** [diecode/KillerMoney#2]
Hi,

I have a problem on my spigot 1.10 server, when a player is opped he have a multiplier of 10 even without any permission, and if he have the negative permission (-killermoney.multiplier.*), it don't change anything, i'm constrained to deop all of my admins. There is a solution to disable this multiplier ?

Thanks.

**Comment by Dragoboss** [comment]
Well, I had a similar problem, my suggestion for the time being is to do
'-killermoney.multiplier.10', '-killermoney.multiplier.9', etc, all the way through to 1, to disable any multiplier.

Although I am not a 100% certain if the multipliers still work the same within yesterday's update that he released on the spigot website, as he said he made some permission system changes....

This is a temporary fix until @diecode responds with a proper fix / can tell you how to fix this yourself.

**Comment by kgahor** [comment]
Could you try the latest ( v3.17 ) version?

**Comment by kgahor** [comment]
Any news with v3.17?
