### ISSUE TITLE
Is there a 1.13 update?

### ISSUE THREAD

**Issue by AsteriskDotHack** [diecode/KillerMoney#20]
My server acknowledges that the mod exists but does not actually work. No monetary gains are added from mob deaths. Sorry for asking here, couldn't find a better place to ask if there are 1.13 build in the works or if i need to switch to another plugin... This truly is my favorite of them all.

**Comment by kgahor** [comment]
I am working on the 1.13 update. I will update it soon! :)

**Comment by AsteriskDotHack** [comment]
That is awesome! I can't wait!

**Comment by AsteriskDotHack** [comment]
Was there an update made for 1.13? The site still sends me to download for the old file.

**Comment by kgahor** [comment]
Yes, I updated to 1.13. I push the source too now
