### ISSUE TITLE
Does not specify API-version

### ISSUE THREAD

**Issue by srnyx** [diecode/KillerMoney#35]
I get this error while trying to load:
`16.11 09:03:45 [Server] WARN Plugin KillerMoney v4.4.0 does not specify an api-version.`

**Comment by srnyx** [comment]
Does this not affect anything?
Because no one has replied...

**Comment by Laarryy** [comment]
@srnyx There's no problem with that [WARN], it's a common sight among many plugins at startup! I'm pretty sure (but not certain) that it has to do with compatibility. Don't worry about it!
